export const ATTENDANCE_STATUS = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  LATE: 'LATE',
  ON_LEAVE: 'ON_LEAVE',
};

export const ATTENDANCE_WINDOW_STATUS = {
  OPEN: 'OPEN',
  COMPLETED: 'COMPLETED',
};

export const STUDENT_HOSTEL_STATUS = {
  ACTIVE: 'active',
  VACATED: 'vacated',
  TRANSFERRED: 'transferred',
  CANCELLED: 'cancelled',
};

export const PASS_STATUS = {
  PENDING_PARENT: 'PENDING_PARENT',
  PENDING_ADMIN: 'PENDING_ADMIN',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
};

export const GATE_EVENT_TYPE = {
  LEFT: 'LEFT',
  RETURNED: 'RETURNED',
};

export const MENTOR_ASSIGNMENT_STATUS = {
  ACTIVE: 'ACTIVE',
  TRANSFERRED: 'TRANSFERRED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

export const PARENT_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
};
